# Luigi Toscano <luigi.toscano@tiscali.it>, 2016. #zanata
# Luigi Toscano <luigi.toscano@tiscali.it>, 2017. #zanata
# Giovanni Grieco <giovanni.grc96@gmail.com>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-06-13 09:18-0400\n"
"PO-Revision-Date: 2018-04-30 08:21+0000\n"
"Last-Translator: Giovanni Grieco <giovanni.grc96@gmail.com>\n"
"Language-Team: Italian\n"
"Language: it\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"X-Generator: Zanata 4.6.2\n"

#: plugins/kickstart.py:57
msgid "Install packages defined in a kickstart file on your system"
msgstr "Installa i pacchetti definiti in un file kickstart sul sistema"

#: plugins/kickstart.py:62
msgid "kickstart file"
msgstr "File di kickstart"

#: plugins/kickstart.py:80
#, python-format
msgid "file cannot be parsed: %s"
msgstr "il file non può essere analizzato: %s"

#: plugins/rpm_conf.py:65
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr "Aggiunta di '{}' all'elenco di pacchetti da far gestire a rpmconf"

#: plugins/rpm_conf.py:71
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr "il plugin rpmconf non verrà eseguito in modalità non-interattiva"

#: plugins/rpm_conf.py:84
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr ""
"viene ignorata la chiamata a sys.exit di rpmconf dovuta alla variable MERGE "
"mancante"

#: plugins/rpm_conf.py:88
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr ""
"viene ignorata la chiamata a sys.exit di rpmconf dovuta ad un file mancante"

#: plugins/showvars.py:46
msgid "show all active dnf variables"
msgstr ""

#: plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr "connessione a snapperd non riuscita: %s"

#: plugins/snapper.py:55
msgid "creating pre_snapshot"
msgstr ""

#: plugins/snapper.py:61
#, python-format
msgid "created pre_snapshot %d"
msgstr ""

#: plugins/snapper.py:65
#, python-format
msgid "creating pre_snapshot failed: %s"
msgstr ""

#: plugins/snapper.py:74
msgid "skipping post_snapshot because creation of pre_snapshot failed"
msgstr ""

#: plugins/snapper.py:80
msgid "creating post_snapshot"
msgstr ""

#: plugins/snapper.py:85
#, python-format
msgid "created post_snapshot %d"
msgstr ""

#: plugins/snapper.py:89
#, python-format
msgid "creating post_snapshot failed: %s"
msgstr ""

#. Translators: This string is only used in unit tests.
#: plugins/system_upgrade.py:45
msgid "the color of the sky"
msgstr "il colore del cielo"

#: plugins/system_upgrade.py:57
msgid "Need a --releasever greater than the current system version."
msgstr ""
"Richiesto un valore di --releasever maggiore della versione attuale del "
"sistema."

#. Translators: do not change "reboot" here
#: plugins/system_upgrade.py:59
#, python-brace-format
msgid ""
"Download complete! Use 'dnf {command} reboot' to start the upgrade.\n"
"To remove cached metadata and transaction use 'dnf {command} clean'"
msgstr ""

#: plugins/system_upgrade.py:62
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr "Bisogna usare l'opzione 'download --releasever' invece di '--network'"

#: plugins/system_upgrade.py:71
msgid "Reboot turned off, not rebooting."
msgstr ""

#: plugins/system_upgrade.py:120
#, python-format
msgid "Screen blanking can't be disabled: %s"
msgstr ""

#: plugins/system_upgrade.py:140
#, python-format
msgid "Failed loading state file: %s, continuing with empty state."
msgstr ""

#: plugins/system_upgrade.py:286
msgid "The following boots appear to contain upgrade logs:"
msgstr ""
"I seguenti precedenti avvii del sistema sembrano contenere dei log di "
"aggiornamenti:"

#: plugins/system_upgrade.py:296
msgid "-- no logs were found --"
msgstr "-- nessun log è stato trovato --"

#: plugins/system_upgrade.py:311
msgid "Cannot find logs with this index."
msgstr "Impossibile trovare log con questo indice."

#: plugins/system_upgrade.py:320
#, fuzzy
msgid "Unable to match systemd journal entry"
msgstr "Non è stato possibile trovare l'inserto sul systemd journal"

#: plugins/system_upgrade.py:341
msgid "Prepare system for upgrade to a new release"
msgstr "Prepara il sistema per l'aggiornamento ad una nuova versione"

#: plugins/system_upgrade.py:357
msgid "keep installed packages if the new release's version is older"
msgstr ""
"mantiene i pacchetti installati se le versioni del nuovo rilascio sono più "
"vecchie"

#: plugins/system_upgrade.py:361
msgid "which logs to show"
msgstr "quali log mostrare"

#: plugins/system_upgrade.py:395
#, python-brace-format
msgid "Incompatible version of data. Rerun 'dnf {command} download [OPTIONS]'"
msgstr ""

#: plugins/system_upgrade.py:432
msgid "Command 'offline-distrosync' cannot be used with --no-downgrade option"
msgstr ""

#: plugins/system_upgrade.py:454
msgid "Additional information for System Upgrade: {}"
msgstr ""

#: plugins/system_upgrade.py:457
msgid ""
"Before you continue ensure that your system is fully upgraded by running "
"\"dnf --refresh upgrade\". Do you want to continue"
msgstr ""
"Prima di continuare assicurarsi che il sistema è completamente aggiornato "
"con \"dnf --refresh upgrade\". Procedere"

#: plugins/system_upgrade.py:461
msgid "Operation aborted."
msgstr "Operazione annullata."

#: plugins/system_upgrade.py:519
msgid "system is not ready for upgrade"
msgstr "il sistema non è pronto per gli aggiornamenti"

#: plugins/system_upgrade.py:522
#, python-brace-format
msgid ""
"the transaction was not prepared for '{command}'. Rerun 'dnf {command} "
"download [OPTIONS]'"
msgstr ""

#: plugins/system_upgrade.py:526
msgid "upgrade is already scheduled"
msgstr "l'aggiornamento è già pianificato"

#: plugins/system_upgrade.py:532
msgid "trigger file does not exist. exiting quietly."
msgstr ""

#: plugins/system_upgrade.py:535
msgid "another upgrade tool is running. exiting quietly."
msgstr ""
"un altro strumento di aggiornamento è in esecuzione, uscita silenziosa."

#: plugins/system_upgrade.py:544
#, python-brace-format
msgid "use 'dnf {command} reboot' to begin the upgrade"
msgstr ""

#: plugins/system_upgrade.py:562
msgid "Rebooting to perform upgrade."
msgstr "Riavvio per effettuare l'aggiornamento."

#: plugins/system_upgrade.py:595
msgid "Starting offline upgrade. This will take a while."
msgstr ""

#: plugins/system_upgrade.py:597
msgid "Starting offline distrosync. This will take a while."
msgstr ""

#: plugins/system_upgrade.py:599
msgid "Starting system upgrade. This will take a while."
msgstr "Avvio dell'aggiornamento del sistema. Ci vorrà un po'."

#: plugins/system_upgrade.py:615
msgid "Cleaning up downloaded data..."
msgstr "Pulizia dei dati scaricati..."

#: plugins/system_upgrade.py:644
msgid ""
"The system-upgrade transaction is empty, your system is already up-to-date."
msgstr ""

#: plugins/system_upgrade.py:653
msgid "Transaction saved to {}."
msgstr ""

#: plugins/system_upgrade.py:656
msgid "Error storing transaction: {}"
msgstr ""

#: plugins/system_upgrade.py:678
msgid "Download finished."
msgstr "Scaricamento completato."

#: plugins/system_upgrade.py:681 plugins/system_upgrade.py:682
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr "Aggiornamento completato! Pulizia e riavvio in corso..."

#: plugins/system_upgrade.py:691
msgid "Prepare offline upgrade of the system"
msgstr ""

#: plugins/system_upgrade.py:696
msgid "Prepare offline distrosync of the system"
msgstr ""

#: plugins/torproxy.py:31
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr ""
"Il plugin torproxy è stato disabilitato: impossibile connettersi alla rete "
"Tor"

#: plugins/tracer.py:69
msgid "For more information run:"
msgstr "Per maggiori informazioni eseguire:"

#: plugins/tracer.py:96
msgid "Call to Tracer API ended unexpectedly:"
msgstr "La chiamata all'API di Tracer è terminata in modo inaspettato:"

#: plugins/tracer.py:98
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""
"Visitare https://github.com/FrostyX/tracer/issues e segnalare il problema.\n"
"Grazie"

#: plugins/tracer.py:100
msgid "We apologize for any inconvenience"
msgstr "Ci scusiamo per i disagi"

#~ msgid "Unable to match package: %s"
#~ msgstr "Non è stato possibile trovare il pacchetto %s"

#~ msgid "Unable to match some of packages"
#~ msgstr "Non è stato possibile trovare alcuni pacchetti"
